# Generated by Django 5.0.6 on 2024-06-13 12:23

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='positive_number',
            field=models.PositiveIntegerField(default=0, validators=[tasks.models.validate_positive]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(validators=[tasks.models.validate_description]),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(validators=[tasks.models.validate_due_date]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, validators=[tasks.models.validate_title]),
        ),
    ]
